# Generated by Django 3.2.5 on 2021-07-16 16:02

import apps.post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210716_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='post/post/default.png', upload_to=apps.post.models.post_thumbnail_path),
        ),
    ]
